echo "# publicwork" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/Generalgree/publicwork.git
git push -u origin main
